# fly.toml app configuration file generated for vstream-bluesky-client on 2024-11-18T12:18:21-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vstream-bluesky-client'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
